---
language: go
dist: trusty
sudo: required

go:
  - 1.8.x
#  - master

env:
  global:
    - CGO_CFLAGS=-I/usr/local/include
    - CGO_LDFLAGS=-L/usr/local/lib

before_install:
- sudo apt-get update -qq
#- sudo apt-get install libgpgme11-dev should be enough, but that would result in a too old libgpgme. so we're compiling manually
- wget -c ftp://ftp.gnupg.org/gcrypt/libgpg-error/libgpg-error-1.27.tar.gz
- wget -c ftp://ftp.gnupg.org/gcrypt/libgcrypt/libgcrypt-1.7.6.tar.gz
- wget -c ftp://ftp.gnupg.org/gcrypt/libassuan/libassuan-2.4.3.tar.bz2
- wget -c ftp://ftp.gnupg.org/gcrypt/libksba/libksba-1.3.5.tar.bz2
- wget -c ftp://ftp.gnupg.org/gcrypt/npth/npth-1.2.tar.bz2
- wget -c ftp://ftp.gnu.org/gnu/ncurses/ncurses-6.0.tar.gz
- wget -c ftp://ftp.gnupg.org/gcrypt/pinentry/pinentry-0.9.5.tar.bz2
- wget -c ftp://ftp.gnupg.org/gcrypt/gnupg/gnupg-2.1.20.tar.bz2
- wget -c ftp://ftp.gnupg.org/gcrypt/gpgme/gpgme-1.9.0.tar.bz2
- tar -xzf libgpg-error-1.27.tar.gz
- tar -xzf libgcrypt-1.7.6.tar.gz
- tar -xjf libassuan-2.4.3.tar.bz2
- tar -xjf libksba-1.3.5.tar.bz2
- tar -xjf npth-1.2.tar.bz2
- tar -xzf ncurses-6.0.tar.gz
- tar -xjf pinentry-0.9.5.tar.bz2
- tar -xjf gnupg-2.1.20.tar.bz2
- tar -xjf gpgme-1.9.0.tar.bz2
- cd libgpg-error-1.27/ && ./configure && make && sudo make install && cd ..
- cd libgcrypt-1.7.6 && ./configure && make && sudo make install && cd ..
- cd libassuan-2.4.3 && ./configure && make && sudo make install && cd ..
- cd libksba-1.3.5 && ./configure && make && sudo make install && cd ..
- cd npth-1.2 && ./configure && make && sudo make install && cd ..
- cd ncurses-6.0 && ./configure && make && sudo make install && cd ..
- cd pinentry-0.9.5 && ./configure --enable-pinentry-curses --disable-pinentry-qt4 && make && sudo make install && cd ..
- cd gnupg-2.1.20 && ./configure && make && sudo make install && cd ..
- cd gpgme-1.9.0 && ./configure && make && sudo make install && cd ..

install:
- true #do not execute "go get ./..." as it will fail with the examples

script:
  - go test -v *.go
